Placeholder spike
quintype/malibu-advanced pull request #232
Opened 2021-07-26 17:54 UTC by Harshith46

# Description

Please include the summary of the change made. Please include the required context here. Please include the issue reference for the fix and the dependencies reference for the change.

Fixes # (issue-reference)

Dependencies # (dependency-issue-reference)

Documentation # (link to the corresponding documentation changes)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test Case A
- [ ] Test Case B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-07-28 09:25 UTC, Athira001 commented on app/isomorphic/components/gumlet-script-generator.js
> +
why are we moving this script from layout.ejs?  We can keep it in partials, right?

2021-07-28 09:25 UTC, Athira001 commented on app/isomorphic/components/story-grid.m.css
> +  background-color: lightgray;
variable?

2021-07-28 09:44 UTC, ags1773 commented on app/isomorphic/components/story-templates/blank.js
> +              styleName={`qt-image-16x9 ${showImagePlaceholder ? "placeholder" : ""}`}
can use a variable to generate styleName string

2021-07-28 11:32 UTC, Harshith46 commented on app/isomorphic/components/gumlet-script-generator.js
> +
we are doing on timeout, not necessary to keep in layout if not required on server side

2021-07-28 11:35 UTC, Harshith46 commented on app/isomorphic/components/story-grid.m.css
> +  background-color: lightgray;
we don't have background-color var

2021-07-28 11:37 UTC, ags1773 approved these changes

2021-08-04 04:30 UTC, Jeevan-Kishore requested changes

2021-08-04 04:30 UTC, Jeevan-Kishore commented on app/client/render.js
> +  const placeholderDelay = get(store.getState(), ["qt", "config", "publisher-attributes", "placeholder_delay"]);
what if a string is inserted?

2021-08-04 04:30 UTC, Jeevan-Kishore commented on app/isomorphic/components/gumlet-script-generator.js
> +    setTimeout(function() {
always clear timeouts!

2021-08-04 04:30 UTC, Jeevan-Kishore commented on app/isomorphic/components/gumlet-script-generator.js
> +import get from "lodash.get";
```suggestion
import get from "lodash/get";
```

2021-08-04 04:30 UTC, Jeevan-Kishore commented on app/isomorphic/components/gumlet-script-generator.js
> +  return <div />;
huh?

2021-08-04 04:30 UTC, Jeevan-Kishore commented on app/isomorphic/components/story-grid.m.css
> +  background-color: lightgray;
create one

2021-08-04 05:07 UTC, Athira001 commented on app/isomorphic/components/gumlet-script-generator.js
> +
Then how the images will load on ssr?

2021-08-04 07:38 UTC, Jeevan-Kishore requested changes

2021-08-04 07:38 UTC, Jeevan-Kishore commented on app/isomorphic/components/gumlet-script-generator.js
> +export const gumletScriptGenerator = () => {
this as a component makes no sense, change to a function..

2021-08-04 07:38 UTC, Jeevan-Kishore commented on app/client/render.js
> +  const placeholderDelay = get(store.getState(), ["qt", "config", "publisher-attributes", "placeholder_delay"]);
this?

2021-08-09 10:35 UTC, merged