feat: auto-sso
quintype/malibu-advanced pull request #325
Opened 2021-10-18 06:50 UTC by phaneendraandukuri

Added support for auto sso 
By default auto sso is disabled, enabling it the performance may affect

Reference: https://github.com/quintype/ace-planning/issues/560

2021-10-18 06:59 UTC, Harshith46 requested changes

2021-10-18 06:59 UTC, Harshith46 commented on app/isomorphic/components/layouts/header/nav-bar/index.js
> +      return currentUserResp;
why return is required?

2021-10-18 06:59 UTC, Harshith46 commented on app/isomorphic/components/layouts/header/nav-bar/index.js
> +      if (window && !user && !queryParamExists) {
the window will be available inside useeffect, its a redundant check

2021-10-18 06:59 UTC, Harshith46 commented on app/isomorphic/components/layouts/header/nav-bar/index.js
> +    if (window) {
check if this condition is required

2021-10-19 11:50 UTC, Harshith46 commented on app/isomorphic/components/layouts/header/nav-bar/index.js
> +      return currentUserResp;
oh yeah, my bad did not see that

2021-10-19 11:50 UTC, Harshith46 commented on app/isomorphic/components/layouts/header/nav-bar/index.js
> +    if (window) {
yeah, but check if it is necessary

2021-10-20 10:12 UTC, shraddha-kesari commented on app/isomorphic/components/layouts/header/nav-bar/index.js
>        );
Yes. We are creating a different branch and doing the change there. As it will not be a blocker for this PR.

2021-10-25 13:05 UTC, merged