Arrow aside collections
quintype/malibu-advanced pull request #476
Opened 2023-01-03 06:44 UTC by VeenaYemmiganur

# Description
Integration of Arrow to Story templates - Passing Template Config / Aside Collection
Fixes # (issue-reference)
https://github.com/quintype/ace-planning/issues/734

2023-01-03 07:20 UTC, Jeevan-Kishore requested changes

2023-01-03 07:20 UTC, Jeevan-Kishore commented on package.json
> +    "node-fetch": "^3.3.0",
do we need this? we have axios & wretch

2023-01-03 07:20 UTC, Jeevan-Kishore commented on app/api/utils.js
> +  const FIELDS =
add in constants.js file

2023-01-06 06:09 UTC, Jeevan-Kishore approved these changes

2023-02-08 11:24 UTC, Jeevan-Kishore requested changes

2023-02-08 11:24 UTC, Jeevan-Kishore commented on app/isomorphic/components/story-templates/listicle-story/index.js
> +      showReadTime: true,
these lines seem to repeat, can we have a function which sends out the config and override as needed using parameters to the same function?

2023-02-08 11:24 UTC, Jeevan-Kishore commented on app/isomorphic/components/story-templates/listicle-story/index.js
> +      showReadTime: true,
```suggestion
const getTemplateConfig = (object) => {{
    templateType: "headline-sideway",
    showSection: true,
    publishedDetails: {
      enablePublishedTime: true,
      enableUpdatedTime: true,
      showReadTime: true,
      }
      }, ...object```

2023-02-09 05:05 UTC, Jeevan-Kishore approved these changes

2023-03-07 04:46 UTC, cricket-lover approved these changes

2023-03-07 06:22 UTC, merged