Redesign AMP heroimage caption
quintype/malibu-advanced pull request #550
Opened 2023-09-22 06:22 UTC by shraddha-kesari

Ref ticket : https://github.com/quintype/ace-planning/issues/877

2023-11-09 04:59 UTC, cricket-lover approved these changes

2023-11-10 04:50 UTC, nandap4790 requested changes

2023-11-10 04:50 UTC, nandap4790 commented on config/publisher.yml
> +sketches_host: https://malibu-advanced-web.quintype.io
Is this intentional ?

2023-11-10 04:50 UTC, nandap4790 requested changes

2023-11-10 04:50 UTC, nandap4790 commented on config/publisher.yml
> +sketches_host: https://malibu-advanced-web.quintype.io
is this intentional ?

2023-11-10 04:52 UTC, shraddha-kesari commented on config/publisher.yml
> +sketches_host: https://malibu-advanced-web.quintype.io
Yes. Most of the times staging is down so.

2023-11-10 05:02 UTC, VeenaYemmiganur approved these changes

2023-12-15 11:06 UTC, nandap4790 approved these changes

2023-12-15 11:26 UTC, shraddha-kesari commented
This is just updating framework version. Updated framework is been pushed by another PR.

2023-12-15 11:26 UTC, closed without merging